[package]
name = "freetype-build"
version = "0.1.0"
authors = ["Fredrik Noren <fredrik.jw.noren@gmail.com>"]
build = "build.rs"

[dependencies]
freetype-rs = "0.6"

[build-dependencies]
cmake = "0.1"
pkg-config = "0.3"
